import{a as S,S as q,i as d}from"./assets/vendor-BjRz3xa9.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const M="https://pixabay.com/api/",P="49633368-6da3d74b0c3b6468a6c14afef";async function u(s,r){try{return(await S.get(M,{params:{key:P,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}})).data}catch(t){throw console.error("Error fetching images:",t),new Error("Failed to fetch images")}}u();let E=new q(".gallery a",{captionsData:"alt",captionDelay:250});const p=document.querySelector(".gallery");function y(s){const r=s.map(t=>`
      <li class="gallery-item">
            <a class="gallery-link" href = '${t.largeImageURL}'> 
                <img class="gallery-image" src = '${t.webformatURL}' alt = '${t.tags}' width = '360'>
            </a>
            <div class = 'info'>
                <div class='descr'><h3>Likes</h3><p>${t.likes}</p></div>
                <div class='descr'><h3>Views</h3><p>${t.views}</p></div>
                <div class='descr'><h3>Comments</h3><p> ${t.comments}</p></div>
                <div class='descr'><h3>Downloads</h3><p>${t.downloads}</p></div>
            </div>
       </li>`).join("");p.insertAdjacentHTML("beforeend",r),E.refresh()}function l(){p.innerHTML=""}const m=document.querySelector(".loader");function g(){m.classList.add("is-active")}function h(){m.classList.remove("is-active")}const f=document.querySelector(".load-more");function v(){f.classList.add("is-active")}function L(){f.classList.remove("is-active")}h();const w=document.querySelector(".form"),$=w.querySelector("input");let c="",i=1;const b=15;w.addEventListener("submit",async s=>{if(s.preventDefault(),l(),i=1,c=$.value.trim(),!!c){g();try{const r=await u(c,i),t=r.totalHits,a=Math.ceil(t/b);r.hits.length?(y(r.hits),i<a&&v()):(l(),L(),d.show({message:"Sorry, there are no images matching your search query. Please try again! ",position:"center",color:"red"}))}catch{l(),d.show({message:"We're sorry, but you've reached the end of search results",position:"center",color:"red"})}h()}});f.addEventListener("click",async()=>{i+=1,g();try{const s=await u(c,i),r=s.totalHits,t=Math.ceil(r/b);y(s.hits);const a=document.querySelector(".gallery-item"),{height:e}=a.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"}),i<t&&v()}catch{L(),d.show({message:"We're sorry, but you've reached the end of search results",position:"bottomCenter",color:"red"})}finally{h()}});
//# sourceMappingURL=index.js.map
