import{a as b,S as P,i as c}from"./assets/vendor-BjRz3xa9.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const S="https://pixabay.com/api/",q="49633368-6da3d74b0c3b6468a6c14afef";async function f(s,r){try{return(await b.get(S,{params:{key:q,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}})).data}catch(t){throw console.error("Error fetching images:",t),new Error("Failed to fetch images")}}let M=new P(".gallery a",{captionsData:"alt",captionDelay:250});const y=document.querySelector(".gallery");function p(s){const r=s.map(t=>`
      <li class="gallery-item">
            <a class="gallery-link" href = '${t.largeImageURL}'> 
                <img class="gallery-image" src = '${t.webformatURL}' alt = '${t.tags}' width = '360'>
            </a>
            <div class = 'info'>
                <div class='descr'><h3>Likes</h3><p>${t.likes}</p></div>
                <div class='descr'><h3>Views</h3><p>${t.views}</p></div>
                <div class='descr'><h3>Comments</h3><p> ${t.comments}</p></div>
                <div class='descr'><h3>Downloads</h3><p>${t.downloads}</p></div>
            </div>
       </li>`).join("");y.insertAdjacentHTML("beforeend",r),M.refresh()}function d(){y.innerHTML=""}const m=document.querySelector(".loader");function g(){m.classList.add("is-active")}function u(){m.classList.remove("is-active")}const h=document.querySelector(".load-more");function v(){h.classList.add("is-active")}h.classList.remove("is-active");u();const w=document.querySelector(".form"),E=w.querySelector("input");let n="",i=1;const L=15;w.addEventListener("submit",async s=>{if(s.preventDefault(),d(),i=1,n=E.value.trim(),!!n){g();try{const r=await f(n,i),t=r.totalHits,a=Math.ceil(t/L);r.hits.length?(p(r.hits),i>=a?c.show({message:"We're sorry, but you've reached the end of search results",position:"center",color:"red"}):v()):(d(),c.show({message:"Sorry, there are no images matching your search query. Please try again! ",position:"center",color:"red"}))}catch{d(),c.show({message:"Failed to fetch images. Please try again later.",position:"center",color:"red"})}u()}});h.addEventListener("click",async()=>{i+=1,g();try{const s=await f(n,i),r=s.totalHits,t=Math.ceil(r/L);p(s.hits),v();const a=document.querySelector(".gallery-item"),{height:e}=a.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"}),i>=t&&c.show({message:"We're sorry, but you've reached the end of search results",position:"center",color:"red"})}catch{c.show({message:"Failed to fetch images. Please try again later.",position:"center",color:"red"})}finally{u()}});
//# sourceMappingURL=index.js.map
